56-no-support-for-ingestion-policies
vmware/terraform-provider-wavefront pull request #57
Opened 2021-01-27 19:00 UTC by snltd

Adds an `ingestion_policy` resource.

Bumps `version` to 2.8.0, but I'm not sure if that file is actually used to create the version. I think 2.8.0 is correct, as this adds a new feature without breaking any compatibility.

2021-01-28 18:54 UTC, keep94 requested changes
Thank you for doing all this work Robert. While you are at it could you do one more small thing? The releases page link under the "Installing the Plugin" section of README.md is wrong.  It should be `https://github.com/vmware/terraform-provider-wavefront/releases` not `https://github.com/WavefrontHQ/terraform-provider-wavefront/releases`

2021-01-28 18:54 UTC, keep94 commented on go.sum
>  github.com/census-instrumentation/opencensus-proto v0.2.1/go.mod h1:f6KPmirojxKA12rnyqOA5BBL4O983OfeGPqjHWSTneU=
Did you remember to run `go mod tidy`?

2021-01-28 18:54 UTC, keep94 commented on wavefront/resource_ingestion_policy.go
> +	policy := wavefront.IngestionPolicy{ID: id}
Nit: You could just do `policy := wavefront.IngestionPolicy{ID: d.Id()}`

2021-01-28 18:54 UTC, keep94 commented on wavefront/resource_ingestion_policy.go
>  	id := d.Id()
I don't think you need the id variable since you don't need a string pointer anymore.

2021-01-29 12:35 UTC, snltd commented
> Thank you for doing all this work Robert. While you are at it could you do one more small thing? The releases page link under the "Installing the Plugin" section of README.md is wrong. It should be `https://github.com/vmware/terraform-provider-wavefront/releases` not `https://github.com/WavefrontHQ/terraform-provider-wavefront/releases`

Done. Also fixed the part that tells you how to run acceptance tests, which was wrong.

2021-01-29 17:19 UTC, keep94 approved these changes
Looks good to me

2021-01-29 17:21 UTC, merged

2021-01-29 19:39 UTC, keep94 commented
snltd,

I have released 2.8.0 of the wavefront terraform plugin, but I forgot to have you update the terraform plugin documentation for your new ingestion_policy_resource, and I forgot to have you update the documentation for service accounts.  I plan to update the documentation myself, but I have one question for you.  What goes in the ingestion_policy field of the wavefront_service_account resource?  The name of the ingestion policy or the ID?